// Code generated by gen_types.go DO NOT EDIT.
package types

var AllTypes = map[string]struct{}{
	"ID": {},
	"INT": {},
	"INT64": {},
	"INT32": {},
	"INT16": {},
	"INT8": {},
	"FLOAT": {},
	"FLOAT32": {},
	"FLOAT64": {},
	"BOOL": {},
	"STRING": {},
	"DATE": {},
	"TIME": {},
	"DATETIME": {},
	"TIMESTAMP": {},
	"DECIMAL": {},
	"NUMERIC": {},
	"UUID": {},
	"BLOB": {},
}
