# Makefile - use `make` or `make help` to get a list of commands.
#
# Note - Comments inside this makefile should be made using a single
# hashtag `#`, lines with double hash-tags will be the messages that
# printed in the help command

# Name of the current directory
PROJECTNAME="orange"

# List of all Go-files to be processed
GOFILES=$(wildcard *.go)

# Docker image variables
IMAGE := $(PROJECTNAME)
VERSION := latest

# Ensures firing a blank `make` command default to help
.DEFAULT_GOAL := help

# Make is verbose in Linux. Make it silent
MAKEFLAGS += --silent


.PHONY: help
## `help`: Generates this help dialog for the Makefile
help: Makefile
	echo
	echo " Commands available in \`"$(PROJECTNAME)"\`:"
	echo
	sed -n 's/^[ \t]*##//p' $< | column -t -s ':' |  sed -e 's/^//'
	echo

.PHONY: repl
## `repl`: Play with orangedb through OQL
repl:
	go run repl/main.go

.PHONY: local-setup
## `local-setup`: Setup development environment locally
local-setup:
	echo "  >  Ensuring directory is a git repository"
	git init &> /dev/null
	echo "  >  Installing pre-commit"
	pip install --upgrade pre-commit &> /dev/null
	pre-commit install


# Will install missing dependencies
.PHONY: install
## `install`: Fetch dependencies needed to run `orange`
install:
	echo "  >  Getting dependencies..."
	go get -v $(get)
	go mod tidy


# No `help` message for this command - designed to be consumed internally
.PHONY: --test-runner
--test-runner:
	go test ./... -covermode=atomic -coverprofile=./coverage/coverage.txt
	go tool cover -html=./coverage/coverage.txt -o ./coverage/coverage.html


.PHONY: test
## :
## `test`: Run all tests
test: export TEST_MODE=complete
test: --test-runner


.PHONY: fast-tests
## `fast-tests`: Selectively run fast tests
fast-tests: export TEST_MODE=fast
fast-tests: --test-runner


.PHONY: slow-tests
## `slow-tests`: Selectively run slow tests
slow-tests: export TEST_MODE=slow
slow-tests: --test-runner


.PHONY: run
## :
## `run`: Run `orange` in production mode
run: export production_mode=production
run: export __BUILD_MODE__=production
run:
	go run main.go $(q)

.PHONY: run-debug
## `run-debug`: Run `orange` in debug mode
run-debug: export debug_mode=debug
run-debug: export __BUILD_MODE__=debug
run-debug:
	go run main.go $(q)


.PHONY: docker-gen
## :
## `docker-gen`: Create a production docker image for `orange`
docker-gen:
	echo "Building docker image \`$(IMAGE):$(VERSION)\`..."
	cp docker/orange/.dockerignore .dockerignore
	docker build --rm \
		--build-arg final_image=scratch \
		--build-arg build_mode=production \
		-t $(IMAGE):$(VERSION) . \
		-f ./docker/orange/Dockerfile
	rm .dockerignore


.PHONY: docker-debug
## `docker-debug`: Create debug-friendly docker images for `orange`
docker-debug:
	echo "Building docker image \`$(IMAGE):$(VERSION)\`..."
	docker build --rm=false \
		--build-arg final_image=golang:1.21 \
		--build-arg build_mode=debug \
		-t $(IMAGE)-debug:$(VERSION) . \
		-f ./docker/Dockerfile


.PHONY: clean-docker
## `clean-docker`: Delete an existing docker image
clean-docker:
	echo "Removing docker $(IMAGE):$(VERSION)..."
	docker rmi -f $(IMAGE):$(VERSION)

.PHONY: clean
## `clean`: Remove build artifacts, logs, and profiles
clean: 
	rm -rf ./benchmark/test
	rm -rf ./benchmark/manifest
	rm -rf ./benchmark/*.log
	rm -rf $(BIN_DIR)
	rm -f ./benchmark.test
	rm -f mem.out cpu.out goroutine.prof coverage/coverage.*


.PHONY: benchmark
## `benchmark`: benchmark io
benchmark:
ifeq ($(filter read,$(MAKECMDGOALS)),read)
	@echo "Running read benchmark..."
	go test -bench=BenchmarkMemtable_Read -memprofile=mem.out -cpuprofile=cpu.out ./benchmark

else ifeq ($(filter write,$(MAKECMDGOALS)),write)
	@echo "Running write benchmark..."

ifeq ($(WAL),on)
	@echo "→ WAL enabled: running only WAL benchmark"
	go test -bench=BenchmarkMemtable_Write_With_WAL -memprofile=mem.out -cpuprofile=cpu.out ./benchmark

else ifeq ($(WAL),off)
	@echo "→ WAL disabled: running only non-WAL benchmark"
	go test -bench=BenchmarkMemtable_Write_Without_WAL -memprofile=mem.out -cpuprofile=cpu.out ./benchmark

else
	@echo "→ No WAL flag provided: running both benchmarks"
	go test -bench=BenchmarkMemtable_Write_With_WAL -memprofile=mem.out -cpuprofile=cpu.out ./benchmark
	make clean
	go test -bench=BenchmarkMemtable_Write_Without_WAL -memprofile=mem.out -cpuprofile=cpu.out ./benchmark
endif

else
	@echo "Usage: make benchmark read | write [WAL=on|off]"
endif


.PHONY: prof
## `prof`: Inspect profiles generated by benchmarks
prof:
ifeq ($(filter cpu,$(MAKECMDGOALS)),cpu)
	go tool pprof ./benchmark.test cpu.out
else ifeq ($(filter goroutines,$(MAKECMDGOALS)),goroutines)
	go tool pprof ./benchmark.test goroutine.prof
else ifeq ($(filter mem,$(MAKECMDGOALS)),mem)
	go tool pprof ./benchmark.test mem.out
else
	@echo "Usage: make prof cpu | goroutines | mem"
endif

## :
##  NOTE: All docker-related commands can use `IMAGE`
## : and `VERSION` variables to modify the docker
## : image being targeted
## :
## : Example;
## :     make docker-gen IMAGE=new_project VERSION=3.15
## :
## : Likewise, both the `run` commands can pass runtime
## : arguments under the `q` arg
## :
## : Example;
## :	`make run q="time --version"`
