// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/proto/ops.proto

package ops

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      string                 `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=columns,proto3" json:"columns,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectReq) Reset() {
	*x = SelectReq{}
	mi := &file_pkg_proto_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectReq) ProtoMessage() {}

func (x *SelectReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectReq.ProtoReflect.Descriptor instead.
func (*SelectReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ops_proto_rawDescGZIP(), []int{0}
}

func (x *SelectReq) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *SelectReq) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *SelectReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SelectRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRes) Reset() {
	*x = SelectRes{}
	mi := &file_pkg_proto_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRes) ProtoMessage() {}

func (x *SelectRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRes.ProtoReflect.Descriptor instead.
func (*SelectRes) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ops_proto_rawDescGZIP(), []int{1}
}

func (x *SelectRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InsertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      string                 `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Value         *structpb.Struct       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertReq) Reset() {
	*x = InsertReq{}
	mi := &file_pkg_proto_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertReq) ProtoMessage() {}

func (x *InsertReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertReq.ProtoReflect.Descriptor instead.
func (*InsertReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ops_proto_rawDescGZIP(), []int{2}
}

func (x *InsertReq) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *InsertReq) GetValue() *structpb.Struct {
	if x != nil {
		return x.Value
	}
	return nil
}

type InsertRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRes) Reset() {
	*x = InsertRes{}
	mi := &file_pkg_proto_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRes) ProtoMessage() {}

func (x *InsertRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRes.ProtoReflect.Descriptor instead.
func (*InsertRes) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ops_proto_rawDescGZIP(), []int{3}
}

func (x *InsertRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type CreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      string                 `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Schema        *structpb.Struct       `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReq) Reset() {
	*x = CreateReq{}
	mi := &file_pkg_proto_ops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReq) ProtoMessage() {}

func (x *CreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
func (*CreateReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ops_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReq) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *CreateReq) GetSchema() *structpb.Struct {
	if x != nil {
		return x.Schema
	}
	return nil
}

type CreatRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatRes) Reset() {
	*x = CreatRes{}
	mi := &file_pkg_proto_ops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatRes) ProtoMessage() {}

func (x *CreatRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatRes.ProtoReflect.Descriptor instead.
func (*CreatRes) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ops_proto_rawDescGZIP(), []int{5}
}

func (x *CreatRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      string                 `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReq) Reset() {
	*x = DeleteReq{}
	mi := &file_pkg_proto_ops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReq) ProtoMessage() {}

func (x *DeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReq.ProtoReflect.Descriptor instead.
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ops_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteReq) GetDocument() string {
	if x != nil {
		return x.Document
	}
	return ""
}

func (x *DeleteReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRes) Reset() {
	*x = DeleteRes{}
	mi := &file_pkg_proto_ops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRes) ProtoMessage() {}

func (x *DeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRes.ProtoReflect.Descriptor instead.
func (*DeleteRes) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ops_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRes) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_pkg_proto_ops_proto protoreflect.FileDescriptor

const file_pkg_proto_ops_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/proto/ops.proto\x12\x03ops\x1a\x1cgoogle/protobuf/struct.proto\"Q\n" +
	"\tSelectReq\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\tR\bdocument\x12\x18\n" +
	"\acolumns\x18\x02 \x03(\tR\acolumns\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\"\x1f\n" +
	"\tSelectRes\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"V\n" +
	"\tInsertReq\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\tR\bdocument\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x05value\"#\n" +
	"\tInsertRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"X\n" +
	"\tCreateReq\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\tR\bdocument\x12/\n" +
	"\x06schema\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06schema\"\"\n" +
	"\bCreatRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"7\n" +
	"\tDeleteReq\x12\x1a\n" +
	"\bdocument\x18\x01 \x01(\tR\bdocument\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"#\n" +
	"\tDeleteRes\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status2\xac\x01\n" +
	"\x03Ops\x12'\n" +
	"\x06Create\x12\x0e.ops.CreateReq\x1a\r.ops.CreatRes\x12(\n" +
	"\x06Insert\x12\x0e.ops.InsertReq\x1a\x0e.ops.InsertRes\x12(\n" +
	"\x06Delete\x12\x0e.ops.DeleteReq\x1a\x0e.ops.DeleteRes\x12(\n" +
	"\x06Select\x12\x0e.ops.SelectReq\x1a\x0e.ops.SelectResB\x0fZ\rpkg/proto/opsb\x06proto3"

var (
	file_pkg_proto_ops_proto_rawDescOnce sync.Once
	file_pkg_proto_ops_proto_rawDescData []byte
)

func file_pkg_proto_ops_proto_rawDescGZIP() []byte {
	file_pkg_proto_ops_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_ops_proto_rawDesc), len(file_pkg_proto_ops_proto_rawDesc)))
	})
	return file_pkg_proto_ops_proto_rawDescData
}

var file_pkg_proto_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_proto_ops_proto_goTypes = []any{
	(*SelectReq)(nil),       // 0: ops.SelectReq
	(*SelectRes)(nil),       // 1: ops.SelectRes
	(*InsertReq)(nil),       // 2: ops.InsertReq
	(*InsertRes)(nil),       // 3: ops.InsertRes
	(*CreateReq)(nil),       // 4: ops.CreateReq
	(*CreatRes)(nil),        // 5: ops.CreatRes
	(*DeleteReq)(nil),       // 6: ops.DeleteReq
	(*DeleteRes)(nil),       // 7: ops.DeleteRes
	(*structpb.Struct)(nil), // 8: google.protobuf.Struct
}
var file_pkg_proto_ops_proto_depIdxs = []int32{
	8, // 0: ops.InsertReq.value:type_name -> google.protobuf.Struct
	8, // 1: ops.CreateReq.schema:type_name -> google.protobuf.Struct
	4, // 2: ops.Ops.Create:input_type -> ops.CreateReq
	2, // 3: ops.Ops.Insert:input_type -> ops.InsertReq
	6, // 4: ops.Ops.Delete:input_type -> ops.DeleteReq
	0, // 5: ops.Ops.Select:input_type -> ops.SelectReq
	5, // 6: ops.Ops.Create:output_type -> ops.CreatRes
	3, // 7: ops.Ops.Insert:output_type -> ops.InsertRes
	7, // 8: ops.Ops.Delete:output_type -> ops.DeleteRes
	1, // 9: ops.Ops.Select:output_type -> ops.SelectRes
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_ops_proto_init() }
func file_pkg_proto_ops_proto_init() {
	if File_pkg_proto_ops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_ops_proto_rawDesc), len(file_pkg_proto_ops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_ops_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ops_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ops_proto_msgTypes,
	}.Build()
	File_pkg_proto_ops_proto = out.File
	file_pkg_proto_ops_proto_goTypes = nil
	file_pkg_proto_ops_proto_depIdxs = nil
}
