# Copyright (c) 2025 Nagaraj Poojari
# SPDX-License-Identifier: MIT
#
# This file is part of: github.com/nagarajRPoojari/parrot
# Licensed under the MIT License.

name: Go Benchmark

on:
  pull_request: 

permissions:
  pull-requests: write
  contents: read

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install deps
      run: go mod download

    - name: Run benchmarks and format results
      run: |
        echo "| Benchmark | Ops/sec |" > benchmark.md
        echo "|-----------|---------|" >> benchmark.md

        make benchmark read > full_benchmark.log
        make benchmark write >> full_benchmark.log

        awk '
          /^BenchmarkMemtable_/ { 
            match($1, /^Benchmark[^-]+/, m); 
            if (m[0] != "") {
              benchmark = m[0]
            }
          }
          /Ops\/sec:/ {
            match($0, /Ops\/sec: ([0-9.]+[MK]?)/, m2)
            if (benchmark != "" && m2[1] != "") {
              printf "| %s | %s |\n", benchmark, m2[1]
            }
          }
        ' full_benchmark.log >> benchmark.md

        cat benchmark.md

    - name: Comment benchmark results on PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: benchmark.md
        comment-id: 0